import{S as d,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m="https://pixabay.com/api/",p="47085214-4cff0ba1bb96c64321ec3a8d9";async function g(r,o=1,i=12){try{const s=new URLSearchParams({key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:i}),e=await fetch(`${m}?${s.toString()}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(s){throw console.error("Error fetching images:",s),s}}const f=document.querySelector(".gallery");function y(r){u(),f.innerHTML=r.map(h).join(""),new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function h({largeImageURL:r,webformatURL:o,tags:i,likes:s,views:e,comments:t,downloads:n}){return`
    <a href="${r}" class="gallery_item">
      <img src="${o}" alt="${i}" class="gallery_image" width="380" loading="lazy"/>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${s}</p>
        <p class="info-item"><b>Views:</b> ${e}</p>
        <p class="info-item"><b>Comments:</b> ${t}</p>
        <p class="info-item"><b>Downloads:</b> ${n}</p>
      </div>
    </a>
  `}function u(){f.innerHTML=""}function b(){l.info({title:"Info",message:"No images found for your search query.",position:"topRight"})}const w=document.querySelector(".loader"),L=document.querySelector(".form");L.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements.query.value.trim();if(!o)return a("Please enter your request");u(),c(!0);try{const i=await g(o);i.hits&&i.hits.length?y(i.hits):b()}catch(i){console.error(i),a("Something went wrong. Please try again!")}finally{c(!1)}});function a(r){l.error({title:"Error",position:"topRight",message:r})}function c(r){w.style.display=r?"block":"none"}
//# sourceMappingURL=index.js.map
