import{S as u,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const d="https://pixabay.com/api/",p="47085214-4cff0ba1bb96c64321ec3a8d9";async function m(r,o=1,s=12){try{const i=new URLSearchParams({key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:s}),e=await fetch(`${d}?${i.toString()}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(i){throw console.error("Error fetching images:",i),i}}const l=document.querySelector(".gallery");function y(r){f(),l.innerHTML=r.map(g).join(""),new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function g({largeImageURL:r,webformatURL:o,tags:s,likes:i,views:e,comments:t,downloads:n}){return`
    <a href="${r}" class="gallery_item">
      <img src="${o}" alt="${s}" class="gallery_image" width="380" loading="lazy"/>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${i}</p>
        <p class="info-item"><b>Views:</b> ${e}</p>
        <p class="info-item"><b>Comments:</b> ${t}</p>
        <p class="info-item"><b>Downloads:</b> ${n}</p>
      </div>
    </a>
  `}function f(){l.innerHTML=""}function h(){c.info({title:"Info",message:"No images found for your search query.",position:"topRight"})}const b=document.querySelector(".loader"),w=document.querySelector(".form");w.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements.query.value.trim();if(!o)return L("Please enter your request");f(),a(!0);try{const s=await m(o);s.hits&&s.hits.length?y(s.hits):h()}catch(s){console.error(s)}finally{a(!1)}});function L(r){c.error({title:"Error",position:"topRight",message:r})}function a(r){b.style.display=r?"block":"none"}
//# sourceMappingURL=index.js.map
